### ISSUE TITLE
License should be CC-BY-SA 3.0, not unlicense

### ISSUE THREAD

**Issue by anothersimulacrum** [AtomicFox556/CDDA-EraOfDecayMod#1]
This contains data lifted directly from DDA, which is licensed under CC-BY-SA 3.0, making this a derivative work, which should be licensed under the same [(or compatible)](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses) license.

**Comment by AtomicFox556** [comment]
Noted; I'm not particularly knowledgeable on legal stuff so this is appreciated. Will change it as soon as I can get to it, though in practice I'd not care what people want to do with it.

**Comment by AtomicFox556** [comment]
License updated by copy-pasting license text from DDA license. Care to confirm the fix?

Edit: if that's why someone blocked me in DDA repository, tell that specific person to go fuck themselves as I can't do that personally now. Some people are too busy to respond within less than a day, so if they don't understand it, they deserve it.

**Comment by anothersimulacrum** [comment]
You have a BSD license there (that's the license for libbacktrace), not [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/legalcode). You can just do as DDA does and have `Cataclysm is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/3.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.`

**Comment by AtomicFox556** [comment]
Apparently I've fucked it up again. Fixed now.

**Comment by anothersimulacrum** [comment]
Looks good, thanks.
